# Generated by Django 3.2.1 on 2021-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourwork',
            options={'ordering': ['date'], 'verbose_name_plural': 'Ourworks'},
        ),
        migrations.AddField(
            model_name='ourwork',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
