# Generated by Django 3.2.1 on 2021-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_email',
            field=models.EmailField(help_text='Please enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Please enter your message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_num',
            field=models.IntegerField(default=None, help_text='Please enter your mobile number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Please enter your name', max_length=100),
        ),
    ]
