# Generated by Django 3.2.1 on 2021-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210519_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_email',
            field=models.EmailField(help_text='required', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='required'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_num',
            field=models.IntegerField(default=None, help_text='required'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='required', max_length=100),
        ),
    ]
