# Generated by Django 3.2.1 on 2021-05-20 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog'),
            preserve_default=False,
        ),
    ]
