# Generated by Django 3.2.1 on 2021-05-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date',), 'verbose_name_plural': 'Blogs'},
        ),
    ]
