# Generated by Django 3.2.1 on 2021-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img_icon',
            field=models.ImageField(null=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(upload_to='service_img'),
        ),
    ]
