# Generated by Django 3.2.1 on 2021-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='news')),
                ('heading', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sub_heading', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'LatestNews',
                'verbose_name_plural': 'LatestNews',
                'ordering': ('heading',),
            },
        ),
    ]
