# Generated by Django 2.0.7 on 2021-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('head', models.CharField(max_length=200)),
                ('sub_head', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
