# Generated by Django 3.2.1 on 2021-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='head',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='num',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='sub_head',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='img',
            field=models.ImageField(default=None, upload_to='testimonials'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='job_position',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
